apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-server
  namespace: default
spec:
  hosts:
  - oauth2.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: oauth2-server
        port:
          number: 9000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: profile-service
  namespace: default
spec:
  hosts:
  - profile.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: profile-service
        port:
          number: 8080
