apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
  namespace: default
  labels:
    app: canary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
      - name: canary-app
        image: gabby.azurecr.io/canary-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OAUTH2_AUTHORIZATION_URI
          value: "https://oauth2.cat-herding.net/oauth2/authorize"
        - name: OAUTH2_CLIENT_ID
          value: "canary-app"
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-app-secrets
              key: demo-client-secret
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app
  namespace: default
spec:
  selector:
    app: canary-app
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
