apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
  namespace: default
  labels:
    app: canary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
      - name: canary-app
        image: gabby.azurecr.io/canary-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OAUTH2_ISSUER_URI
          value: "https://oauth.bigboy.example.com"
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app
  namespace: default
spec:
  selector:
    app: canary-app
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
