apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-ui
  namespace: default
  labels:
    app: profile-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-ui
  template:
    metadata:
      labels:
        app: profile-ui
    spec:
      containers:
      - name: profile-ui
        image: gabby.azurecr.io/profile-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_FORWARD_HEADERS_STRATEGY
          value: "native"
        - name: PROFILE_UI_PORT
          value: "8080"
        - name: OAUTH2_ISSUER_URI
          value: "https://oauth2.cat-herding.net"
        - name: OAUTH2_CLIENT_ID
          value: "profile-ui"
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-app-secrets
              key: demo-client-secret
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-ui
  namespace: default
spec:
  selector:
    app: profile-ui
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
