apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oauth2-keystore-provider
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: oauth2-keystore-secret
      type: Opaque
      data:
        - objectName: oauth2-tls-keystore
          key: keystore.p12.b64
        - objectName: oauth2-tls-keystore-password
          key: keystore.password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    # userAssignedIdentityID: "" # Uncomment and set if using user-assigned managed identity
    keyvaultName: inker-kv
    tenantId: "42ddc44e-97dd-4c3b-bf8a-31c785e24c67"
    objects: |
      array:
        - |
          objectName: oauth2-tls-keystore
          objectType: secret
        - |
          objectName: oauth2-tls-keystore-password
          objectType: secret
