apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oauth2-secrets-provider
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: oauth2-app-secrets
      type: Opaque
      data:
        - objectName: oauth2-tls-keystore
          key: keystore.p12.b64
        - objectName: oauth2-tls-keystore-password
          key: keystore.password
        - objectName: oauth2-db-url
          key: database-url
        - objectName: oauth2-db-username
          key: database-username
        - objectName: oauth2-db-password
          key: database-password
        - objectName: oauth2-demo-client-secret
          key: demo-client-secret
        - objectName: oauth2-m2m-client-secret
          key: m2m-client-secret
        - objectName: oauth2-demo-user-password
          key: demo-user-password
        - objectName: oauth2-admin-user-password
          key: admin-user-password
        - objectName: oauth2-issuer-url
          key: issuer-url
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e502213f-1f15-4f03-9fb4-b546f51aafe9"
    keyvaultName: inker-kv
    tenantId: "42ddc44e-97dd-4c3b-bf8a-31c785e24c67"
    objects: |
      array:
        - |
          objectName: oauth2-tls-keystore
          objectType: secret
        - |
          objectName: oauth2-tls-keystore-password
          objectType: secret
        - |
          objectName: oauth2-db-url
          objectType: secret
        - |
          objectName: oauth2-db-username
          objectType: secret
        - |
          objectName: oauth2-db-password
          objectType: secret
        - |
          objectName: oauth2-demo-client-secret
          objectType: secret
        - |
          objectName: oauth2-m2m-client-secret
          objectType: secret
        - |
          objectName: oauth2-demo-user-password
          objectType: secret
        - |
          objectName: oauth2-admin-user-password
          objectType: secret
        - |
          objectName: oauth2-issuer-url
          objectType: secret
