apiVersion: v1
kind: Secret
metadata:
  name: oauth2-app-secrets
  namespace: default
type: Opaque
stringData:
  issuer-url: ""
  database-url: ""
  database-name: ""
  database-username: ""
  database-password: ""
  demo-client-secret: ""
  m2m-client-secret: ""
  demo-user-password: ""
  admin-user-password: ""
  keystore.p12.b64: ""
  keystore.password: ""
  redis-password: ""
  github-client-id: ""
  github-client-secret: ""
  google-client-id: ""
  google-client-secret: ""
  azure-client-id: ""
  azure-client-secret: ""
  azure-tenant-id: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-jwk-secret
  namespace: default
type: Opaque
stringData:
  static-jwk: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: profile-service-secrets
  namespace: default
type: Opaque
stringData:
  mongodb-uri: ""
  mongodb-database: ""
  redis-uri: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: default
type: Opaque
stringData:
  redis-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
  namespace: default
type: Opaque
stringData:
  chat-client-secret: ""
  chat-oauth-hmac-secret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: github-review-secrets
  namespace: default
type: Opaque
stringData:
  openai-api-key: ""
  github-token: ""
  redis-uri: ""
