apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: security-agency-secrets-provider
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: security-agency-secrets
      type: Opaque
      data:
        - objectName: security-agency-client-secret
          key: client-secret
        - objectName: security-agency-oauth-hmac-secret
          key: security-agency-oauth-hmac-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e502213f-1f15-4f03-9fb4-b546f51aafe9"
    keyvaultName: inker-kv
    tenantId: "42ddc44e-97dd-4c3b-bf8a-31c785e24c67"
    objects: |
      array:
        - |
          objectName: security-agency-client-secret
          objectType: secret
        - |
          objectName: security-agency-oauth-hmac-secret
          objectType: secret
