apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-review-secrets-provider
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: github-review-secrets
      type: Opaque
      data:
        - objectName: github-token
          key: github-token
        - objectName: openai-api-key
          key: openai-api-key
        - objectName: redis-uri
          key: redis-uri
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e502213f-1f15-4f03-9fb4-b546f51aafe9"
    keyvaultName: inker-kv
    tenantId: "42ddc44e-97dd-4c3b-bf8a-31c785e24c67"
    objects: |
      array:
        - |
          objectName: github-token
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: redis-uri
          objectType: secret
