apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: profile-service-secrets-provider
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: profile-service-secrets
      type: Opaque
      data:
        # MongoDB configuration used by profile-service
        - objectName: profile-ui-mongodb-uri
          key: mongodb-uri
        - objectName: profile-ui-mongodb-database
          key: mongodb-database
        # Redis URI used by profile-service
        - objectName: redis-uri
          key: redis-uri
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e502213f-1f15-4f03-9fb4-b546f51aafe9"
    keyvaultName: inker-kv
    tenantId: "42ddc44e-97dd-4c3b-bf8a-31c785e24c67"
    objects: |
      array:
        - |
          objectName: profile-ui-mongodb-uri
          objectType: secret
        - |
          objectName: profile-ui-mongodb-database
          objectType: secret
        - |
          objectName: redis-uri
          objectType: secret
