apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oauth2-server-deployment.yaml
  - oauth2-server-serviceaccount-rbac.yaml
  - oauth2clients.yaml
  - oauth2client-secrets.yaml
  - oauth2scopes.yaml
