apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-server
  namespace: default
  labels:
    app: oauth2-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth2-server-oauth2clients
  namespace: default
  labels:
    app: oauth2-server
rules:
  # Allow the oauth2-server to CRUD OAuth2Client custom resources.
  - apiGroups: ["oauth.bootsandcats.com"]
    resources: ["oauth2clients", "oauth2clients/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Allow the oauth2-server to CRUD OAuth2DenyRule custom resources.
  - apiGroups: ["oauth.bootsandcats.com"]
    resources: ["oauth2denyrules", "oauth2denyrules/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Optional (only needed if oauth2.audit.kubernetes-events.enabled=true): allow emitting Events.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # Optional (only needed if using spec.secretRef): allow reading Secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth2-server-oauth2clients
  namespace: default
  labels:
    app: oauth2-server
subjects:
  - kind: ServiceAccount
    name: oauth2-server
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oauth2-server-oauth2clients
