apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-oauth2-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: 'e502213f-1f15-4f03-9fb4-b546f51aafe9'
    keyvaultName: 'inker-kv'
    cloudName: ''
    objects: |
      array:
        - |
          objectName: chat-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: chat-oauth-hmac-secret
          objectType: secret
          objectVersion: ""
    tenantId: '42ddc44e-97dd-4c3b-bf8a-31c785e24c67'
  secretObjects:
    - secretName: chat-oauth2-secrets
      type: Opaque
      data:
        - objectName: chat-client-secret
          key: client-secret
        - objectName: chat-oauth-hmac-secret
          key: hmac-secret
