apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-chat-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: 'e502213f-1f15-4f03-9fb4-b546f51aafe9'
    keyvaultName: 'ai-chat-kv-1763873634'
    cloudName: ''
    objects: |
      array:
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: REDIS-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: REDIS-HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: REDIS-PORT
          objectType: secret
          objectVersion: ""
        - |
          objectName: OAUTH2-CLIENT-ID
          objectType: secret
          objectVersion: ""
        - |
          objectName: OAUTH2-CLIENT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: OAUTH2-COOKIE-SECRET
          objectType: secret
          objectVersion: ""
    tenantId: '42ddc44e-97dd-4c3b-bf8a-31c785e24c67'
  secretObjects:
    - secretName: chat-secrets-from-keyvault
      type: Opaque
      data:
        - objectName: OPENAI-API-KEY
          key: OPENAI_API_KEY
        - objectName: REDIS-PASSWORD
          key: REDIS_PASSWORD
        - objectName: REDIS-HOST
          key: REDIS_HOST
        - objectName: REDIS-PORT
          key: REDIS_PORT
        - objectName: OAUTH2-CLIENT-ID
          key: OAUTH2_CLIENT_ID
        - objectName: OAUTH2-CLIENT-SECRET
          key: OAUTH2_CLIENT_SECRET
        - objectName: OAUTH2-COOKIE-SECRET
          key: OAUTH2_COOKIE_SECRET
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-openai-secret
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: 'e502213f-1f15-4f03-9fb4-b546f51aafe9'
    keyvaultName: 'ai-chat-kv-1763873634'
    cloudName: ''
    objects: |
      array:
        - |
          objectName: OPENAI-API-KEY
          objectType: secret
          objectVersion: ""
    tenantId: '42ddc44e-97dd-4c3b-bf8a-31c785e24c67'
  secretObjects:
    - secretName: kv-openai-secret
      type: Opaque
      data:
        - objectName: OPENAI-API-KEY
          key: OPENAI_API_KEY
