apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oauth2-server
  - profile-service
  - github-review-service

  # Shared operational resources
  - configs/flyway-migrations-configmap.yaml
  - configs/pdb.yaml
