apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../oauth2-server-deployment.yaml
  - ../profile-service-deployment.yaml
  - ../github-review-service-deployment.yaml
  - ../flyway-migrations-configmap.yaml
  - ../pdb.yaml
