apiVersion: v1
kind: ConfigMap
metadata:
  name: security-agency-oauth2-sds
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    project: bootsandcats
data:
  security-agency-oauth2-sds.yaml: |
    resources:
    - "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
      name: security-agency-oauth-token
      generic_secret:
        secret:
          inline_string: "PLACEHOLDER_WILL_BE_RENDERED_BY_INIT_CONTAINER"
    - "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
      name: security-agency-oauth-hmac
      generic_secret:
        secret:
          inline_string: "PLACEHOLDER_WILL_BE_RENDERED_BY_INIT_CONTAINER"
