# ProxyConfig sets default sidecar resource requests/limits
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    app: istio-system
data:
  mesh: |
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      # Set default sidecar resource requests and limits
      resources:
        limits:
          cpu: 100m
          memory: 128Mi

