apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - istio-proxy-config.yaml
  - istio-authz-policy.yaml
  - requestauthentication-default.yaml
  - virtualservices.yaml
  - telemetry.yaml
  - postgres-mtls.yaml
  - postgres-peer-auth.yaml
  - envoyfilter-secure-subdomain-oauth2.yaml
  - envoyfilter-secure-subdomain-jwt.yaml
  - envoy-oauth2-sds-configmap-secure-subdomain.yaml

