apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-authz-policy.yaml
  - requestauthentication-profile.yaml
  - envoyfilter-profile-oauth2-exchange.yaml
  - envoyfilter-profile-jwt-to-headers.yaml
  - requestauthentication-github-review.yaml
  - envoyfilter-github-review-oauth2-exchange.yaml
  - envoyfilter-github-review-jwt-to-headers.yaml
  - requestauthentication-chat.yaml
  - envoyfilter-chat-oauth2-exchange.yaml
  - envoyfilter-chat-jwt-to-headers.yaml
  - envoy-oauth2-sds-configmap.yaml
  - serviceentry-oauth2.yaml
  - virtualservices.yaml
