apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-proxy-config.yaml
  - istio-authz-policy.yaml
  - requestauthentication-profile.yaml
  - requestauthentication-github-review.yaml
  - envoyfilter-github-review-oauth2-exchange.yaml
  - envoyfilter-github-review-jwt-to-headers.yaml
  - envoy-oauth2-sds-configmap.yaml
  - virtualservices.yaml
  - envoyfilter-profile-service-oauth2-exchange.yaml
  - envoyfilter-profile-service-jwt-to-headers.yaml
  - telemetry.yaml
  - postgres-mtls.yaml
  - postgres-peer-auth.yaml
  - envoyfilter-slop-detector-oauth2-exchange.yaml
  - envoyfilter-slop-detector-jwt-to-headers.yaml
  - requestauthentication-slop-detector.yaml
  - envoy-oauth2-sds-configmap-slop-detector.yaml
