apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: postgres-mtls
  namespace: default
spec:
  host: postgres.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
