apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: postgres-peer-auth
  namespace: default
spec:
  selector:
    matchLabels:
      postgresql: postgres-ha
  mtls:
    mode: STRICT
