apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-server
  namespace: default
  annotations:
    networking.istio.io/exportTo: "*"
spec:
  hosts:
  - oauth2.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: oauth2-server
        port:
          number: 9000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: profile-service
  namespace: default
spec:
  hosts:
  - profile.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: profile-service
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: github-review-service
  namespace: default
spec:
  hosts:
  - gh-review.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gh-review
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: slop-detector
  namespace: default
spec:
  hosts:
  - slop-detector.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: slop-detector
        port:
          number: 80
