apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-server
  namespace: default
  annotations:
    networking.istio.io/exportTo: "*"
spec:
  hosts:
  - oauth2.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /_oauth2/
    route:
    - destination:
        host: oauth2-proxy.aks-istio-ingress.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: oauth2-server
        port:
          number: 9000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: profile-service
  namespace: default
spec:
  hosts:
  - profile.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /_oauth2/
    route:
    - destination:
        host: oauth2-proxy.aks-istio-ingress.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: profile-service
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: github-review-service
  namespace: default
spec:
  hosts:
  - gh-review.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /_oauth2/
    route:
    - destination:
        host: oauth2-proxy.aks-istio-ingress.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gh-review
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: slop-detector
  namespace: default
spec:
  hosts:
  - slop-detector.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /_oauth2/
    route:
    - destination:
        host: oauth2-proxy.aks-istio-ingress.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: slop-detector
        port:
          number: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: security-agency
  namespace: default
spec:
  hosts:
  - security-agency.cat-herding.net
  gateways:
  - aks-istio-ingress/cat-herding-gateway
  http:
  - match:
    - uri:
        prefix: /_oauth2/
    route:
    - destination:
        host: oauth2-proxy.aks-istio-ingress.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: security-agency
        port:
          number: 80
